edition                     = "2021"
max_width                   = 80
tab_spaces                  = 2
format_code_in_doc_comments = true
normalize_comments          = true
normalize_doc_attributes    = true
