name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish the module"
        required: false
        default: true
        type: boolean

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
      packages: write
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      build-artifact-id: ${{ steps.artifact.outputs.artifact-id }}
      build-artifact-url: ${{ steps.artifact.outputs.artifact-url }}
      build-artifact-digest: ${{ steps.artifact.outputs.artifact-digest }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: canary

      - id: check
        name: run checks
        run: |
          deno lint
          deno fmt --check
          deno test -A --no-check=remote --permit-no-files
          deno doc --lint mod.ts

      - id: build
        name: build wasm
        run: deno task build

      - id: artifact
        if: steps.build.outcome == 'success'
        name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: brotli-build-${{ github.sha }}
          path: lib

      - id: publish
        if: |
          steps.check.outcome == 'success' &&
          steps.build.outcome == 'success' && (
            (
              github.event_name == 'workflow_dispatch' &&
              github.event.inputs.publish == 'true'
            ) || (
              github.event_name == 'push' &&
              startsWith(github.ref, 'refs/tags/')
            )
          )
        name: publish to jsr
        run: deno publish --dry-run --allow-dirty && deno publish --allow-dirty
